plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.3.cjs

npmRegistries:
  "https://npm.pkg.github.com/":
    npmAlwaysAuth: true
    # 빈 문자열을 fallback 값으로 설정
    npmAuthToken: ${GITHUB_NPM_AUTH_TOKEN-''}